#!/bin/bash
## test home
testdir=$(cd $(dirname $0)/; pwd)
## word home
workdir=$(dirname $testdir)
cd $workdir

module=mailsender
app=tycs-$module
pidfile=var/app.pid
logfile=var/app.log
control=./control
httpprex="127.0.0.1:1986"

## statistics
function statistics(){
    curl -s "$httpprex/counter/all" | python -m json.tool
}

## config
function config(){
    action=$1
    case $action in
        "reload")
            curl -s "$httpprex/config/reload" | python -m json.tool
            ;;
        *)
            curl -s "$httpprex/config" | python -m json.tool
            ;;
    esac
}

## tail
function tail_log(){
    $control tail
}

## debug
function send_mail(){
    receivers=$1
    subject=$2
    content=$3
    user=$4
    # "nieanan@xiaomi.com" "主题subject" "邮件内容，content" ["anan.nie"]
    body="tos=$receivers;subject=$subject;content=$content"
    if [ "X$user" != "X" ];then
        body=$body";user=$user"
    fi
    curl -s -X POST -d $body "$httpprex/mail/sender" | python -m json.tool
}

## build
function build(){
    $control build
}
function start(){
    $control start
}
function stop(){
    $control stop
}

action=$1
case $action in
    "build")
        build
        ;;
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        stop; build && start
        ;;
    "config")
        config $2
        ;;
    "tail")
        tail_log
        ;;
    "mail")
        send_mail $2 $3 $4 $5
        ;;
    *)
        statistics 
        ;;
esac

